# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDB-RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'SnapKit'
	pod 'SDWebImage'
	pod 'RxSwift', '6.6.0'
    	pod 'RxCocoa', '6.6.0'
	pod 'Alamofire'

  # Pods for TMDB-RxSwift

end
